name: Build & Deploy
on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: 20.10.0
      - run: npm i yarn -g

      - name: Deploy Messenger App
        uses: appleboy/ssh-action@v0.1.2
        with:
          host: ${{secrets.SSH_HOST}}
          key: ${{secrets.SSH_KEY}}
          username: ${{secrets.SSH_USERNAME}}

          script: |
            export NVM_DIR=~/.nvm
            source ~/.nvm/nvm.sh

            cd /var/www/messenger

            git pull origin main
            cd api
            npm run build

            pm2 delete index
            pm2 start dist/src/index.js

            cd ../client
            yarn build

            sudo service nginx restart
            echo 'Deployment successful'
